project:
  type: website
  output-dir: _site

website:
  title: "McPherson Group"
  description: "Research Group Website"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
        menu:
          - href: research-data-science.qmd
            text: "Data Science & Computational Methods"
          - href: research-statistical-modeling.qmd
            text: "Statistical Modeling & Analysis"
          - href: research-interdisciplinary.qmd
            text: "Interdisciplinary Collaborations"
          - href: research-open-science.qmd
            text: "Open Science & Reproducible Research"
      - href: publications.qmd
        text: Publications
      - href: people.qmd
        text: People

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
