project:
  type: website
  output-dir: _site
  render:
    - "**/*.qmd"
    - "**/*.md"
    - "!research/CONFERENCE_README.md"
    - "!**/README.md"

website:
  title: "McPherson Group"
  favicon: images/logo.ico
  description: "Research Group Website"
  navbar:
    background: primary
    search: true
    logo: images/logo.svg
    left:
      - href: index.qmd
        icon: house
        text: Home
      - href: about.qmd
        icon: info-circle
        text: About
      - href: research/index.qmd
        icon: graph-up
        text: Research
        menu:
          - href: research/infectiousdiseases.qmd
            text: "Infectious Diseases"
          - href: research/humangutmicrobiome.qmd
            text: "Human Gut Microbiome"
          - href: research/antimicrobialresistance.qmd
            text: "Antimicrobial Resistance"
          - href: research/antimicrobialstewardship.qmd
            text: "Statistical Modeling & Analysis"
      - href: publications/index.qmd
        icon: mortarboard
      - href: people/index.qmd
        icon: people
        text: People
      - href: people/join.qmd
        icon: person-plus
        text: Join
        aria-label: Join
    right:
      - icon: envelope
        href: mailto:jacobmcpherson@utexas.edu;jkmcpherson@uh.edu;jacob@jacobkmcpherson.com
        aria-label: Email
      - icon: calendar-date
        href: https://calendar.app.google/hFWaGJn7qYa74EYaA
        aria-label: Calendar
      - icon: building
        href: https://jacobkmcpherson.com/
        aria-label: Business
      - icon: github
        href: https://github.com/McPhersonGroup
        aria-label: GitHub
  page-footer:
    left: "Copyright © 2025 Jacob K. McPherson, PharmD, PhD - All Rights Reserved"
    right: 
      - text: "License"
        href: LICENSE.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
