project:
  type: website
  output-dir: _site

website:
  title: "McPherson Group"
  description: "Research Group Website"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        icon: house
        text: Home
      - href: about.qmd
        icon: info-circle
        text: About
      - href: research/index.qmd
        icon: graph-up
        text: Research
        menu:
          - href: research/infectiousdiseases.qmd
            text: "Infectious Diseases"
          - href: research/humangutmicrobiome.qmd
            text: "Human Gut Microbiome"
          - href: research/antimicrobialresistance.qmd
            text: "Antimicrobial Resistance"
          - href: research/antimicrobialstewardship.qmd
            text: "Statistical Modeling & Analysis"
      - href: publications/index.qmd
        icon: mortarboard
      - href: people/index.qmd
        icon: people
        text: People
      - href: people/join.qmd
        icon: person-plus
        text: Join
        aria-label: Join
    right:
      - icon: book
        href: https://author.link/JacobKMcPherson
        aria-label: Author.Link
      - icon: calendar-date
        href: https://jacobkmcpherson.com/schedule
        aria-label: Calendar
      - icon: envelope
        href: mailto:jacobmcpherson@utexas.edu
        aria-label: Email
      - icon: building
        href: https://jacobkmcpherson.com
        aria-label: Business
      - icon: house-gear
        href: https://github.com/McPhersonGroup
        aria-label: GitHub
  page-footer:
    left: "© 2025 Jacob K. McPherson"
    right: 
      - text: "License"
        href: LICENSE.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
