project:
  type: website
  output-dir: _site

website:
  title: "McPherson Group"
  description: "Research Group Website"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
        menu:
          - href: research-data-science.qmd
            text: "Data Science & Computational Methods"
          - href: research-statistical-modeling.qmd
            text: "Statistical Modeling & Analysis"
          - href: research-interdisciplinary.qmd
            text: "Interdisciplinary Collaborations"
          - href: research-open-science.qmd
            text: "Open Science & Reproducible Research"
      - href: publications.qmd
        text: Publications
      - href: people.qmd
        text: People
    right:
      - icon: book
        href: https://author.link/JacobKMcPherson
        aria-label: Author.Link
      - icon: calendar
        href: https://jacobkmcpherson.com/schedule
        aria-label: Calendar
      - icon: envelope
        href: mailto:jacobmcpherson@utexas.edu
        aria-label: Email
      - icon: globe
        href: https://jacobkmcpherson.com
        aria-label: Website
      - icon: linkedin
        href: https://linkedin.com/in/jacobkmcpherson/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/McPhersonGroup
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
