project:
  type: website
  output-dir: _site

website:
  title: "McPherson Group"
  description: "Research Group Website"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
        menu:
          - href: research/infectiousdiseases.qmd
            text: "Infectious Diseases"
          - href: research/humangutmicrobiome.qmd
            text: "Human Gut Microbiome"
          - href: research/antimicrobialresistance.qmd
            text: "Antimicrobial Resistance"
          - href: research/antimicrobialstewardship.qmd
            text: "Statistical Modeling & Analysis"
      - href: people/index.qmd
        text: People
    right:
      - icon: book
        href: https://author.link/JacobKMcPherson
        aria-label: Author.Link
      - icon: calendar-date
        href: https://jacobkmcpherson.com/schedule
        aria-label: Calendar
      - icon: envelope
        href: mailto:jacobmcpherson@utexas.edu
        aria-label: Email
      - icon: building
        href: https://jacobkmcpherson.com
        aria-label: Business
      - icon: linkedin
        href: https://linkedin.com/in/jacobkmcpherson/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/McPhersonGroup
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
