---
title: "Research"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: true
  filter-ui: true
page-layout: full
title-block-banner: false
css: styles.css
---

<!--- # Research Areas -->

Our group conducts pharmacological research across four main areas:


::: {.grid}

::: {.g-col-4}
[**Infectious Diseases**](research/infectiousdiseases.qmd)

Pharmacy practice of pharmacokinetics / pharmacodynamics (PK/PD) to susceptible or resistant organisms

:::

::: {.g-col-4}
[**Antimicrobial Stewardship**](research/antimicrobialstewardship.qmd)

Pharmacy practice of antimicrobial stewardship and economic justification

:::

::: {.g-col-4}
[**Antimicrobial Resistance**](research/antimicrobialresistance.qmd)

Spatiotemporal genomic epidemiology and pharmacology

:::

::: {.g-col-4}
[**Human Gut Microbiome** ](research/humangutmicrobiome.qmd)

Dynamics and Host-Microbe Interactions

:::

::: {.g-col-4}

[**Drug Development**](research/drugdevelopment.qmd)

Antibiotics, probiotics, antifungals, and antivirals

:::

::: {.g-col-4}

[**Economic Analysis**](research/economicanalysis.qmd)


:::

:::


## Current Projects

### Project 1: \[Project Title\]

Brief description of ongoing research project and its significance.

### Project 2: \[Project Title\]

Brief description of ongoing research project and its significance.



## Collaborations

We actively collaborate with researchers from various institutions and disciplines to address complex research questions.

## Funding

Our research is supported by grants from:

-   \[Funding Agency 1\]
-   \[Funding Agency 2\]
-   \[Funding Agency 3\]
